### ISSUE TITLE
Filter by Network Does Not Filter Past First Page

### ISSUE THREAD

**Issue by mykcryptodev** [thirdweb-dev/dashboard#1204]
Introduced in #1192 

See a video here on steps to reproduce:
https://www.loom.com/share/c3df2cd252474514b35e9772bcfb9f9f

I can take on creating a PR to address it

**Comment by MananTank** [comment]
This PR fixes the issue - https://github.com/thirdweb-dev/dashboard/pull/1205

**Comment by mykcryptodev** [comment]
> This PR fixes the issue - #1205

Sorry @MananTank just saw this - I also opened #1206 just now. Ill give your branch a quick test!

**Comment by mykcryptodev** [comment]
Heads up that I can get two Show More buttons - I'll see if I can whip up a fix for that 

![Screen Shot 2023-05-12 at 7 42 15 PM](https://github.com/thirdweb-dev/dashboard/assets/89474773/a19b4a17-ba73-49e0-a809-99572c0dc74d)

**Comment by MananTank** [comment]
Let's go with https://github.com/thirdweb-dev/dashboard/pull/1206
