### ISSUE TITLE
claim button is missing in token drop dashboard

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-dev/dashboard#1234]
The claim button is not visible on the Token Drop page.
![image](https://github.com/thirdweb-dev/dashboard/assets/15052701/cd3186de-8274-4097-80a5-e1c7dc5e393e)

The only way to claim the ERC-20 token is via Explorer or Embed.

**Comment by ptdatta** [comment]
@warengonzaga  is this issue still open to work?

**Comment by warengonzaga** [comment]
Hey @ptdatta let's ask @nachoiacovino about this.

**Comment by ptdatta** [comment]
@nachoiacovino Can I work on this?
