### ISSUE TITLE
Problem in viewing the wallet after signing(accepting terms and conditions)

### ISSUE THREAD

**Issue by subhash131** [thirdweb-dev/dashboard#1240]
![image](https://github.com/thirdweb-dev/dashboard/assets/64570322/7f94d09f-a84f-49bc-80a4-f65906276288)
Connected the wallet to dashboard
next it asks for a signature
![image](https://github.com/thirdweb-dev/dashboard/assets/64570322/8d6b51f2-2eaa-4e00-898f-5f5f51631854)
Signed the transaction but still the pop up do not disappears
![image](https://github.com/thirdweb-dev/dashboard/assets/64570322/70f12bb6-8618-4801-8741-683056f23c1d)

**Comment by MananTank** [comment]
@subhash131 This issue has been fixed, Are you still facing this issue?
