### ISSUE TITLE
Trying to `yarn dev` and getting a bunch of error

### ISSUE THREAD

**Issue by kien-ngo** [thirdweb-dev/dashboard#1355]
I forked and cloned the project. After running `yarn install`, I tried `yarn dev` but it's giving me these error in the browser console.

`localhost:3000/`:
![image](https://github.com/thirdweb-dev/dashboard/assets/26052673/c3ce637d-bf3f-4abc-abbc-49f4f66de71d)

What am I missing?
Tagging mah man @MananTank since you've helped me a lot in the past ^^

Update: so it works well on my Linux machine but not on my Windows desktop >.<

**Comment by MananTank** [comment]
@kienngo98 Are you using yalc?

**Comment by kienngo98** [comment]
@MananTank Nope I'm not using yalc. I cloned the repo and now just trying to run it locally with yarn dev.

This issue seems to be with the Windows OS, since I don't have any issue on linux.

**Comment by kien-ngo** [comment]
Ok so that problem was Node version. I was using 16.16, upgrading to 18.x helps solve the issue (I feel stupid right now). Thanks anyway!
