### ISSUE TITLE
Pagination visual bug

### ISSUE THREAD

**Issue by warengonzaga** [thirdweb-dev/dashboard#1391]
If you have a token of around 110 and your item display limits to 50 it only shows to pages instead of 3 pages to accommodate the remaining 10 tickets.

## Replication

1. Deploy a contract, any drop contracts.
2. Upload a total of 110 tokens.
3. Try to limit it to 50 tokens per page.
4. Navigate to the last page, you'll not be able to see the last 10 tokens.

cc: @MananTank @nachoiacovino

**Comment by kien-ngo** [comment]
I'm working on this @warengonzaga - can confirm the issue happens to me too

**Comment by kien-ngo** [comment]
Fixed. Can close now

**Comment by MananTank** [comment]
Thanks a lot @kien-ngo !
