### ISSUE TITLE
Embed Preview Not Loading

### ISSUE THREAD

**Issue by ac12644** [thirdweb-dev/dashboard#1447]
The Embed Preview feature for the `Marketplace v2.0.0` contract is currently not loading as expected. The section displays a blank area.

<img width="2021" alt="Screenshot 2023-07-26 at 15 38 37" src="https://github.com/thirdweb-dev/dashboard/assets/43683452/e665f6fe-aec6-4527-b251-ed075e7e7d68">

**Comment by kien-ngo** [comment]
@ac12644 Are you still having this issue? I'm happy to take a look if you can share the link to your marketplace contract

**Comment by MananTank** [comment]
@ac12644 Can you share the dashboard link?

**Comment by ac12644** [comment]
Yes still having issue @kien-ngo @MananTank 
here is the link: https://thirdweb.com/mumbai/0x87a5A885B7d7D584347e25F3C7a235a98aB870b4/embed

**Comment by kien-ngo** [comment]
Interesting. It loads just fine for me & I couldn't find any error in the console. It might have something to do with where you're located. I'll let @MananTank take over
![image](https://github.com/thirdweb-dev/dashboard/assets/26052673/275c56a1-a9c8-4a0c-9dfb-06bff4b47bcb)

**Comment by ac12644** [comment]
Issue fixed it was Chrome browser issue blocking third party cookies. thank you @kien-ngo
