### ISSUE TITLE
MetaMask Wallet Errors in Console 

### ISSUE THREAD

**Issue by CalculatingZero** [thirdweb-dev/dashboard#1680]
<img width="665" alt="Screenshot 2023-09-16 at 12 19 52 AM" src="https://github.com/thirdweb-dev/dashboard/assets/20590197/b95fc550-4499-4266-9c82-e94519052872">

I noticed these errors on the thirdweb site and my web app as well (which uses thirdweb's wallet). It seems to have to do with the wallet connection to metamask. Any thoughts on this? I saw this in the MM github issues:

https://github.com/MetaMask/metamask-extension/issues/20847#issuecomment-1721749685

When logged out of the MM wallet the console does not show any errors.

**Comment by MananTank** [comment]
Hey @CalculatingZero - This error is logged by the MetaMask extension itself
