### ISSUE TITLE
Incorrect Getting Started code snippet for custom network  

### ISSUE THREAD

**Issue by jarrodwatts** [thirdweb-dev/dashboard#1732]
Deploy smart contract to a custom network, e.g. a network I created called "cranegeode"

The getting started code snippet says this (screenshot), but really I need to add the details in my code manually.

![incorrect code snippet](https://github.com/thirdweb-dev/dashboard/assets/35651410/07f40ecd-7132-415f-94bc-d4696570de83)

**Comment by jarrodwatts** [comment]
I think it's this code on `code-overview.tsx`, but I didn't look too closely:

```tsx
      ?.replace(
        /{{chainName}}/gm,
        !chainName || chainName?.startsWith("0x") || chainName?.endsWith(".eth")
          ? '"ethereum"'
          : preSupportedSlugs.includes(chainName as any)
          ? `"${chainName}"`
          : env === "javascript"
          ? getExportName(chainName)
          : `{ ${getExportName(chainName)} }`,
      )
```

**Comment by jnsdls** [comment]
yep, good find. Working on an overhaul of how custom networks work as we speak. We'll fix this as part of it. Should be no more than ~ a week.
