### ISSUE TITLE
Zilliqa EVM Testnet (assume same issue on Zilliqa EVM Mainnet) Gas price 100000000000 lower than minimum allowable 4761904761904

### ISSUE THREAD

**Issue by darthgus** [thirdweb-dev/dashboard#2016]
Hi there.

Request from @warengonzaga to raise the issue here.

We are currently attempting to deploy any smart contract from the dashboard, and we click "deploy now", another box pops up saying deploying, then we get the following error;

Failed to deploy contract
Couldn't deploy CREATE2 factory: {"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-26,"data":null,"message":"GasPrice 100000000000 lower than minimum allowable 4761904761904"},"stack":"{\n

![image](https://github.com/thirdweb-dev/dashboard/assets/41507311/06f1148d-a411-4aab-9d47-fec9bf9d9039)

If you need me to provide anything else, please let me know.

thirdweb's Token contract --> i used this one, but we seem to get the same error on any of the premade contracts.

**Comment by warengonzaga** [comment]
Hey @joaquim-verges or @MananTank can you take a look into this? Thanks!

**Comment by darthgus** [comment]
Hey @warengonzaga we still have heard nothing about our issue??

**Comment by jnsdls** [comment]
please reach out via https://support.thirdweb.com/
