### ISSUE TITLE
Listings are not removed after the purchase

### ISSUE THREAD

**Issue by MukhamejanKaratayev** [thirdweb-dev/dashboard#207]
Hello guys, 

First of all, thank you very much for sharing such a great tool with everyone. 

I am working on my NFT marketplace to mint and list items using this dashboard. However, when I buy listed NFT at my custom marketplace, it disappears from the active listing on the marketplace, however, it is still shown in the list of listings on the thirdweb/dashboard. I am working on the Rinkeby test network if it is important. By the way, the purchase functionality works great, the ownership is transferred and etc. 

Could you please help to fix this issue, so the listing is automatically canceled when the item is purchased? 

Thanks a lot in advance.

**Comment by jnsdls** [comment]
Will finally be fixed with this: https://github.com/thirdweb-dev/dashboard/pull/585 (letting u toggle between active / all listings in the dashboard)
