### ISSUE TITLE
 It seems like there is a version issue with @tanstack/react-query.

### ISSUE THREAD

**Issue by KoreanDinosaurs** [thirdweb-dev/dashboard#2084]
It has been confirmed that @thirdweb-dev/react is currently using version ^4.33.0 of @tanstack/react-query.

Are there any plans to adopt version 5 of @tanstack/react-query?
If not, does that imply that my only option is to downgrade to version 4.33.0?

When I attempt to use version 5 of @tanstack/react-query, the following error occurs.
I am currently using next@^14.0.2 and react@^18.

<img width="772" alt="Screen Shot 2023-12-24 at 6 37 51 PM" src="https://github.com/thirdweb-dev/dashboard/assets/97653052/55cc9f06-3d5b-4224-b19a-43c519706c58">

**Comment by jnsdls** [comment]
https://github.com/thirdweb-dev/js/issues/2709
