### ISSUE TITLE
Properties column in contract item overview needs overflow

### ISSUE THREAD

**Issue by baringji** [thirdweb-dev/dashboard#247]
In some instances, when creating an item definition attributes they will have long text, causing the `Properties` column overflow. Leaving the `Claimed Supply` and `Actions` hidden and needed to be scrolled.

Affects also the UI for settings of that item

![Screenshot from 2022-07-10 10-05-47](https://user-images.githubusercontent.com/2443223/178128657-5cbba364-2650-4c2b-aa72-4b3be7f8d472.png)
.

**Comment by jnsdls** [comment]
properties are now displayed in the "details drawer" only and have an overflow in there
