### ISSUE TITLE
Single Point of Failure Found: unpkg.com

### ISSUE THREAD

**Issue by MananTank** [thirdweb-dev/dashboard#695]
## Problem 
A CSS file is loaded from unpkg.com and it is a SPOF

<img width="702" alt="image" src="https://user-images.githubusercontent.com/22043396/205310351-18dc634f-d70f-4fba-be27-910c6ee7f0c4.png">

If unpkg.com goes down or responds very slowly, the website does not render anything because rendering is blocked by that CSS file

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/22043396/205310177-0032c431-9520-4de0-82a5-461cabe5412a.png">

WebPageTest Report: https://www.webpagetest.org/video/compare.php?tests=221202_AiDc8Q_96D,221202_AiDcWE_96F

---

## Solution

Self-host this CSS file instead of relying on unpkg.com

**Comment by jnsdls** [comment]
good find, been looking to get rid of react-vis in the project actually, but we still have 1 single graph based on it left in the splits contract page. The idea of self-hosting it instead is fine (though I do unpkg.com is a decent host and we should be fine in general).

If you want to throw up a PR to self-host it I'd happily take it @MananTank, if not we'll tackle it (one way or another) soon.
