### ISSUE TITLE
Poor Rendering Performance caused by CSS blur filter

### ISSUE THREAD

**Issue by MananTank** [thirdweb-dev/dashboard#703]
## Problem 

UI rendering performance is very poor and there are a lot of dropped frames when scrolling the page. 

## Root Cause  
This is happening because `filter: blur` CSS is used to create the Aurora effect. 

`filter: blur` filter is extremely taxing on CPU/GPU and should be avoided for creating Aurora effect ( because that requires applying the blur on a large element with a large blur radius )

If we remove the `filter:blur` CSS - rendering issues get resolved

See the attached video:

https://user-images.githubusercontent.com/22043396/205436880-744b5634-27d2-4b63-8ee1-d5e125648720.mp4

## Solution

Instead of creating the blur at runtime with CSS - just use an image 

See https://cosmos.network/ for example

---

### Tested on

Hardware: Macbook Pro 16" (2021) (M1 Pro)
Browser: Chrome 107

**Comment by jnsdls** [comment]
good find, would happily accept a PR that solves this while keeping the visuals the same / compatibly similar

**Comment by MananTank** [comment]
@jnsdls I created an aurora image using Figma and a react sandbox to try it out

Check out this [Sandbox](https://zxbvtt.csb.app/) ( [Code](https://codesandbox.io/s/magical-sunset-zxbvtt?file=/src/Aurora/Aurora.js) ) 

What do you think?

**Comment by jnsdls** [comment]
@MananTank looks good! my only concern would be the possibility of the image "popping in" but it seems like you've largely solved that. I also think depending on how large the aurora is we may be able to prioritize the loading of it / embed it as base64 if absolutely necessary (or mark it as needing to be pre-loaded at least)

do you want to take a stab at making a PR to replace the css blur gradient with your aurora png approach?

**Comment by MananTank** [comment]
@jnsdls 

In the sandbox, the Image loading is quite slow because the request is sent after JS execution. I wanted to preload the image in the sandbox but I couldn't do it because Codesandbox changes the URL of the image request sent via JS compared to the one preloaded in the HTML file. The Image would be loaded much earlier in the Thirdweb's Next.js app. Also, the image I have used is not perfect - it's quite large (~500kB) and should be optimized to improve image loading
 
I have created an optimized image. If you check the sandbox's public folder - there are two versions of the image - a WebP (~100kB) and a PNG (~500kB). WebP looks almost as good as PNG one but it has some artifacts of compression (only visible when you look really closely). 

I used the Google Chrome team's [Squoosh App](https://squoosh.app/) to optimize the PNG to WebP but I'm not 100% satisfied with the output so I used the PNG one for the demo sandbox. I would like to try out a few more tools to optimize the PNG size without compromising the quality. I don't trust Nextjs's Image component to do that properly for a gradient image, So we will have to do it manually. 

Once we have an optimized image, We can start with the preloading approach, it should load the image super quickly (and also try the fade-in animation on the image like the sandbox to gracefully load the image) but if that does not feel good and we want to start rendering the UI with the image already there, then we can try out the base64 encoding approach and compare which feels the best ( and also test its impact on page load perf metrics like FCP and LCP )

---

I'm happy to do a PR for this - but I will be quite busy this week and may not be able to work on it this week. If you are fine with that, you can leave this one to me 👍

(However, If you do decide to implement it yourself, Make sure to add `overflow:hidden` style to your App container element (not the body!) to make sure there are no horizontal and vertical overflows caused by aurora images - refer to the sandbox for example )

**Comment by jnsdls** [comment]
All sounds good, will see if we get to it this week but likely won't so unless otherwise noted this one is all yours! 🎉

**Comment by jnsdls** [comment]
> Code

I lied, merged it just now - but there's more to do on perf side for sure

**Comment by MananTank** [comment]
@jnsdls 🚨
 
The Aurora blur appears to be much smaller than it used to be - It looks a bit weird now

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/22043396/205888774-3ccc4734-a659-4974-9df6-6ee68f3b43b1.png">


<br />

Before: https://thirdweb-n9d5q39ri.thirdweb-preview.com/

After: https://thirdweb-ipuya0hks.thirdweb-preview.com/

**Comment by jnsdls** [comment]
fixed, thx - it does need a max width otherwise it ends up wayy to big on large resolutions but 66vw was too small

**Comment by MananTank** [comment]
@jnsdls I think the current `max-width:80vw` is also a bit too small for regular desktop screen size. I would suggest doing the same thing that I have done in the sandbox and avoid setting max-widths altogether.

* Put the image inside the section (element with max-width)  
* use `width:200%` + `max-width:none` on the image ( you can use continue using 400% for mobile/tablet )

This will make it so the image has the proper size (200% of section width) no matter what the device-width


See the below video for Example:

https://user-images.githubusercontent.com/22043396/206031930-a8be1cb9-cdc0-4f40-aedd-54bba0f1fc29.mp4
