### ISSUE TITLE
[Question] How can I get the values for the env variables?

### ISSUE THREAD

**Issue by MananTank** [thirdweb-dev/dashboard#728]
I couldn't find documentation on how to get the values for the environment variables. 

If it is documented somewhere, Can you please give me the link to it? ( It would be a good idea to include that in the README ) and If it is not documented - Can you add it to the README?

I have been using placeholder values for the environment variables but I'm having trouble with it when running the `next build` and I would like to properly set up my local environment so that I can build pages properly

**Comment by jnsdls** [comment]
I'll go through the flow of setting it up from scratch and add the instructions to the readme (and also update the example env file) thanks for the callout!

**Comment by MananTank** [comment]
@jnsdls I thought the wrong env values were creating issues with invariants 

Any idea why this is happening when I am trying to do the `next build` ?

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/22043396/207429483-7f16e531-8868-4ce9-9cbb-558abcd20426.png">

Without setting up any env variables, I get this error:

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/22043396/207430716-5d9cdb17-e95c-4e49-97f6-25e7badede5a.png">

**Comment by MananTank** [comment]
Nevermind, I cloned the repo again and ran `next build` and It worked without any errors
