### ISSUE TITLE
Random behavior with text rendering

### ISSUE THREAD

**Issue by MananTank** [thirdweb-dev/dashboard#758]
Usually, on the first load ( and sometimes even after that ) - the website is not using the "Inter" font-family and uses the fallback "sans-serif" to render the text. But when we reload the page - the issue gets resolved.

To replicate this issue, Load the website in incognito, and check the font-family:

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/22043396/209622533-17ef9500-cf98-4a67-a92c-104573646e2a.png">

Then reload the page, and check again:

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/22043396/209622860-79824b8f-d603-4b8a-a0df-94da3baae5ec.png">

**Comment by jnsdls** [comment]
I believe this is a @next/font issue, if that's the case others will be running into it, too
